language: node_js

node_js:
  - 4
  - 6
  - 8

addons:
  firefox: "49.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

cache: yarn

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - yarn check-ci
  - yarn install --production
  - yarn build
